### ISSUE TITLE
Angular js with dev extreme

### ISSUE THREAD

**Issue by Supriya-Infinx** [DevExpress/DevExtreme#10252]
var app = angular.module('app', [
   'dx'
]);

I am getting this error

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module dx due to:
Error: [$compile:baddir] Directive name 'DOMComponent' is invalid. The first character must be a lowercase letter
http://errors.angularjs.org/1.4.3/$compile/baddir?p0=DOMComponent
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:68:12
    at assertValidDirectiveName (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:6905:13)
    at $CompileProvider.registerDirective [as directive] (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:6932:7)
    at runInvokeQueue (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4356:35)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4364:11
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4363:40
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)

**Comment by AlisherAmonulloev** [comment]
Please let us know if the issue persists. I will do my best to find an appropriate solution for you.

**Comment by AlisherAmonulloev** [comment]
I am going to close this thread since there has not been any recent activity. Feel free to reopen it if our assistance if required.
