### ISSUE TITLE
DataGrid -  The "Failed to execute 'querySelectorAll'" error occurs on focusing the input

### ISSUE THREAD

**Issue by HASSANDL** [DevExpress/DevExtreme#10292]
show below error when add row and show popup form and when click input edit form
devextreme, devextreme-react: 19.2.2-beta
```
dom_adapter.js:23 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '[id='dx-query-children'] td[tabindex]:focus, [id='dx-query-children']  tr[tabindex]:not(.dx-data-row):focus, [id='dx-query-children']  input:focus, [id='dx-query-children']  textarea:focus, [id='dx-query-children']  .dx-lookup-field:focus, [id='dx-query-children']  .dx-checkbox:focu' is not a valid selector.
    at Object.querySelectorAll (http://localhost:3000/static/js/6.chunk.js:278234:20)
    at Object.object.<computed> [as querySelectorAll] (http://localhost:3000/static/js/6.chunk.js:284549:34)
    at initRender.push../node_modules/devextreme/core/renderer_base.js.initRender.find (http://localhost:3000/static/js/6.chunk.js:280429:44)
    at inheritor._getFocusedElement (http://localhost:3000/static/js/6.chunk.js:370365:29)
    at inheritor._updateFocusCore (http://localhost:3000/static/js/6.chunk.js:370377:21)
    at http://localhost:3000/static/js/6.chunk.js:370404:14
```

**Comment by artem-kurchenko** [comment]
Hi,

I cannot reproduce the issue in v19.2.3 using this [example](https://codesandbox.io/s/form-editing-devextreme-data-grid-le1e3). 
Please modify it and post the updated link here for further research.
