### ISSUE TITLE
Gantt v0.0.27 error

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#10883]
Hi, after update on version v0.0.27 there is an error occures:

```
TypeError: this.ganttOwner.getHeaderHeight is not a function
    at GanttView.calculateEtalonSizeValuesCore (http://localhost:8094/node_modules/devexpress-gantt/dist/dx-gantt.js:4207:65)
    at GanttView.calculateEtalonSizeValues (http://localhost:8094/node_modules/devexpress-gantt/dist/dx-gantt.js:4192:14)
    at new GanttView (http://localhost:8094/node_modules/devexpress-gantt/dist/dx-gantt.js:4125:14)
    at t.value (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:118:8476)
    at t._renderComponent (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:16:4385)
    at t.endUpdate (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:16:8573)
    at t.endUpdate (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:10:4766)
    at t.endUpdate (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:10:20184)
    at t.endUpdate (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:10:4766)
    at t.ctor (http://localhost:8094/node_modules/devextreme/dist/js/dx.all.js:20:1840) undefined
```

**Comment by natashaash** [comment]
Hello,
I assume that you updated the [devexpress-gantt package](https://www.npmjs.com/package/devexpress-gantt) separately. So, the problem occurs because the node_modules folder in your project contains an older version of the [DevExtreme package](https://www.npmjs.com/package/devextreme).
I suggest that you don't update separate packages ( in particular, devexpress-gantt). You need to update the whole DevExtreme package to avoid such dependency issues.

**Comment by Bykiev** [comment]
Thanks, yes, I've updated devexpress-gantt package separately, because devextreme updating only once in month, but devexpress-gantt updates more often.
