### ISSUE TITLE
DevExtreme Theme Builder: accept CSS/LESS/SASS variables

### ISSUE THREAD

**Issue by julesrx** [DevExpress/DevExtreme#19376]
The DevExtreme Theme Builder does not accept CSS variables or any variables (LESS/SASS).

### Steps to Reproduce:

1. create a theme on the theme builder
2. replace values with css variables
3. build the theme using the `build-theme` command

### Results You Received:
Build error:
```
> build
> devextreme build-theme --input-file ./dx.generic.json --output-file ./dx.generic.css

Using version 21.1.5.
Error: Compilation failed. bundle: [object Object], file: C:\Users\jules\Downloads\dx-theme\node_modules\devextreme-themebuilder\data\scss\widgets\generic\button\_colors.scss line: 360 $color: var(--brand-color) is not a color.
    ╷
360 │   $button-default-border-color: darken($base-accent, 5%) !default;
    │                                 ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\devextreme-themebuilder\data\scss\widgets\generic\button\_colors.scss 360:33  @use
  node_modules\devextreme-themebuilder\data\scss\widgets\generic\list\_colors.scss 4:1       @use
  node_modules\devextreme-themebuilder\data\scss\widgets\generic\list\_sizes.scss 2:1        @use
  node_modules\devextreme-themebuilder\data\scss\widgets\generic\common\_mixins.scss 7:1     @use
  node_modules\devextreme-themebuilder\data\scss\widgets\generic\typography\_index.scss 6:1  @use
  node_modules\devextreme-themebuilder\data\scss\bundles\dx.light.scss 3:1                   root stylesheet
    at CompileManager.<anonymous> (C:\Users\jules\Downloads\dx-theme\node_modules\devextreme-themebuilder\modules\compile-manager.js:70:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\jules\Downloads\dx-theme\node_modules\devextreme-themebuilder\modules\compile-manager.js:6:65)
```

### Results You Expected:
Successful build.

### Proposed solution:
When building the theme, if a css variable is present, require the import of a secondary CSS/LESS/SASS file containing the definitions for the variables :
```bash
$ devextreme build-theme --input-file ./dx.generic.json --variables-file ./variables.{css,less,scss,sass} --output-file ./dx.generic.css
```

### Environment Details:
package.json:
```json
{
  "name": "dx-theme-css-variables",
  "private": "true",
  "scripts": {
    "build": "devextreme build-theme --input-file ./dx.generic.json --output-file ./dx.generic.css"
  },
  "devDependencies": {
    "devextreme-cli": "^1.2.21",
    "devextreme-themebuilder": "^21.1.5"
  }
}
```

Theme file:
```json
{
    "items": [
        {
            "key": "$base-accent",
            "value": "var(--brand-color)"
        }
    ],
    "baseTheme": "generic.light",
    "outputColorScheme": "custom-scheme",
    "makeSwatch": false,
    "version": "21.1.5",
    "widgets": [],
    "removeExternalResources": false
}
```

**Comment by babich-a** [comment]
Hi @julesrx
We use [sass color functions](https://sass-lang.com/documentation/modules/color) to calculate colors that are dependent on $accent-color. They do not accept CSS variables. So, the `value` property of the`items` array can be a color only.

If you need to customize the compiling process, you can use [scss files from package](https://unpkg.com/browse/devextreme@21.1.5/scss/bundles/).

**Comment by julesrx** [comment]
I'll do this thanks.
