### ISSUE TITLE
DateBox - The "the date should be in range after the selection" test fails on the 31st day of a month

### ISSUE THREAD

**Issue by San4es** [DevExpress/DevExtreme#6748]
```
DevExpress.ui.widgets.editors/datebox.tests.js - datebox w/ time list: the date should be in range after the selection

1. date is correct
Expected: "2016-11-05T12:00:00.000Z"
Result: "2016-12-05T12:00:00.000Z"
Source:
    at Object.eval (http://localhost:20030/testing/tests/DevExpress.ui.widgets.editors/datebox.tests.js!transpiled:3019:24)
    at runTest (http://localhost:20030/node_modules/qunitjs/qunit/qunit.js:1478:30)
    at Test.run (http://localhost:20030/node_modules/qunitjs/qunit/qunit.js:1464:6)
    at http://localhost:20030/node_modules/qunitjs/qunit/qunit.js:1670:12
    at advance (http://localhost:20030/node_modules/qunitjs/qunit/qunit.js:1116:26)

```

**Comment by San4es** [comment]
Fixed in #6753 (18_2),  https://github.com/DevExpress/DevExtreme/commit/40d7d2eb39d93dc0cafc5ac0c1bfce7b14cfb6d5 (19_1), #6767 (18_1)
