### ISSUE TITLE
Error in code compiled of Devextreme 19.1.5 (DateBox mask)

### ISSUE THREAD

**Issue by pedrofurtado** [DevExpress/DevExtreme#9659]
@BingoRUS 

In the file `https://unpkg.com/browse/devextreme@19.1.5/ui/date_box/ui.date_box.mask.js`, on line `38` there is the following code:

```javascript
return originalHandlers[(0, _utils.normalizeKeyName)(e)].apply(_this, [e])
```

That is the compiled result of this line on `https://github.com/DevExpress/DevExtreme/blob/19_2/js/ui/date_box/ui.date_box.mask.js#L24`:

```javascript
const callOriginalHandler = (e) => originalHandlers[normalizeKeyName(e)].apply(this, [e]);
```

But the minified code gives me the following sentry error:

```
TypeError: n[i.normalizeKeyName(...)] is undefined
  at o/<(./node_modules/devextreme/ui/date_box/ui.date_box.mask.js:56:31)
  at applyHandler(./node_modules/devextreme/ui/date_box/ui.date_box.mask.js:55:31)
  at func(./node_modules/devextreme/ui/date_box/ui.date_box.mask.js:107:16)
  at this(./node_modules/devextreme/ui/widget/ui.widget.js:600:21)
  at method(./node_modules/devextreme/ui/date_box/ui.date_box.mask.js:165:18)
  at this(./node_modules/devextreme/core/class.js:20:14)
  at _this(./node_modules/devextreme/ui/widget/ui.keyboard_processor.js:135:42)
  at handler(./node_modules/devextreme/ui/widget/ui.keyboard_processor.js:63:9)
  at callHandler(./node_modules/devextreme/events/core/events_engine.js:151:20)
  at handleObject(./node_modules/devextreme/events/core/events_engine.js:181:11)
  at eventData(./node_modules/devextreme/events/core/events_engine.js:275:11)
  at handlersController(./node_modules/devextreme/events/core/events_engine.js:280:7)
  at fn(./node_modules/devextreme/events/core/events_engine.js:293:5)
  at i(./node_modules/@sentry/browser/esm/helpers.js:87:14)
```

![Capturar](https://user-images.githubusercontent.com/10530520/64645391-32871680-d3eb-11e9-82d4-2722b9bfe85d.PNG)

The compiled line of code is correct? :+1:

**Comment by pedrofurtado** [comment]
Any news?

**Comment by mrjohn0011** [comment]
Hello. I cannot reproduce this issue in the English locale. This error may occur when you press an unsupported key while dxDateBox is opened. 

Please provide me with a codepen example with your locale and describe steps to reproduce this issue.

**Comment by DokaRus** [comment]
Hi,
I've reproduced the issue on my side and created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T817164/datebox-an-error-occurs-when-the-right-arrow-is-pressed-when-the-editor-has-the-time-type) in our SC. You can subscribe to it to receive a notification once we have any progress.

**Comment by pedrofurtado** [comment]
@DokaRus Thanks man! I have a login in the Devextreme support center, but i cannot see the internal issue. Can I see it? Or just the devextreme team could view the ticket?

Anyway, thanks @BingoRUS @DokaRus and @mrjohn0011 for your help and work in Devextreme 🤝 🎉

**Comment by pedrofurtado** [comment]
@DokaRus This link is the same than yours, right? 

https://www.devexpress.com/Support/Center/Question/Details/T817164/datebox-an-error-occurs-when-the-right-arrow-is-pressed-when-the-editor-has-the-time-type

**Comment by DokaRus** [comment]
Oh, my fault
Yep, that's it
