### ISSUE TITLE
Error in compiled code of Devextreme 19.1.6 Scheduler (ui.scheduler.appointments.strategy.base.js)

### ISSUE THREAD

**Issue by pedrofurtado** [DevExpress/DevExtreme#9883]
@BingoRUS @mrjohn0011 @DokaRus Hey guys! 🤝 

In the file `https://unpkg.com/browse/devextreme@19.1.6/ui/scheduler/rendering_strategies/ui.scheduler.appointments.strategy.base.js`, on line 416 there is the following code:

```javascript
indexes[resultItem.index] = false;
```

That is the compiled result of this line on 
`https://github.com/DevExpress/DevExtreme/blob/ad892e4e2a797055504aeba462bea3f60b9a9842/js/ui/scheduler/rendering_strategies/ui.scheduler.appointments.strategy.base.js#L379`.

But the minified code gives me the following sentry error:

```
TypeError: h is undefined
  at this(./node_modules/devextreme/ui/scheduler/rendering_strategies/ui.scheduler.appointments.strategy.base.js:477:11)
  at _get(./node_modules/devextreme/ui/scheduler/rendering_strategies/ui.scheduler.appointments.strategy.base.js:157:29)
  at _get(./node_modules/devextreme/ui/scheduler/rendering_strategies/ui.scheduler.appointments.strategy.horizontal_month_line.js:170:14)
  at this(./node_modules/devextreme/ui/scheduler/rendering_strategies/ui.scheduler.appointments.strategy.horizontal_month.js:235:14)
  at this(./node_modules/devextreme/ui/scheduler/ui.scheduler.appointments.layout_manager.js:129:27)
  at method(./node_modules/devextreme/ui/scheduler/ui.scheduler.js:903:26)
  at list(./node_modules/devextreme/core/class.js:20:14)
  at this(./node_modules/devextreme/core/utils/callbacks.js:27:18)
  at this(./node_modules/devextreme/core/utils/callbacks.js:96:7)
  at callbacks(./node_modules/devextreme/core/utils/callbacks.js:106:3)
  at fn(./node_modules/devextreme/core/utils/resize_callbacks.js:53:5)
  at i(./node_modules/@sentry/browser/esm/helpers.js:87:14)
```

![screencapture-sentry-lbv-org-br-lbv-social-frontend-issues-6777-2019-09-25-10_15_01](https://user-images.githubusercontent.com/10530520/65604444-e658dc00-df7d-11e9-9bdf-3d90e332c902.png)

This situation is similar to #9659 . Possibly this occurs because of "null pointer exceptions" (in this case, a position that cannot exist in the array `indexes`).

I will also try to emulate this in a CodePen. But i suspect that this bug (in its origin) is similar to the issue #9659 .

Anyway, thank you much your your help guys, and your great work in Devextreme! 🎉

**Comment by pedrofurtado** [comment]
@BingoRUS @mrjohn0011 @DokaRus I'm trying to emulate this bug locally in a codepen 👍 🤝

**Comment by pedrofurtado** [comment]
@andrewmakarov I can provide more informations about this, if necessary :+1: to help to identify the root of problem :handshake:

**Comment by pedrofurtado** [comment]
@DokaRus @andrewmakarov It was possible to reproduce the bug? 🤝

**Comment by andrewmakarov** [comment]
Hi @pedrofurtado 
 replied to your inquiry in [t821898](https://supportcenter.devexpress.com/ticket/details/t821898/error-in-compiled-code-of-devextreme-19-1-6-scheduler-ui-scheduler-appointments-strategy). Please let us know if once you re-create the issue in a stand-alone example
